/**
 * 初中：人教版《英语》七年级至八年级 · 原创示例（非教材原文）
 */
export const juniorUnits = [
  {
    order: 1,
    chapter: '七上 Unit 1',
    title: 'Good Morning!',
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 1',
    learn: [
      ['Good morning, Alice.', ['Good', 'morning,', 'Alice.']],
      ['How are you today?', ['How', 'are', 'you', 'today?']],
    ],
    listen: [
      { sentence: 'My name is Alan.', correct: 'name', choices: ['name', 'game', 'same', 'late'] },
      { sentence: 'Nice to meet you too.', correct: 'meet', choices: ['meet', 'meat', 'mean', 'meal'] },
      { sentence: 'What is this in English?', correct: 'English', choices: ['English', 'England', 'language', 'orange'] },
      { sentence: 'Spell it, please.', correct: 'Spell', choices: ['Spell', 'Sell', 'Still', 'Spill'] },
      { sentence: 'The quilt is purple.', correct: 'purple', choices: ['purple', 'people', 'puple', 'paper'] },
      { sentence: 'I can say the letters.', correct: 'letters', choices: ['letters', 'leaders', 'liters', 'lettuce'] },
    ],
  },
  {
    order: 2,
    chapter: '七上 Unit 2',
    title: 'This Is My Sister',
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 2',
    learn: [
      ['This is my sister Anna.', ['This', 'is', 'my', 'sister', 'Anna.']],
      ['Those are my parents.', ['Those', 'are', 'my', 'parents.']],
    ],
    listen: [
      { sentence: 'That is my brother.', correct: 'brother', choices: ['brother', 'mother', 'father', 'sister'] },
      { sentence: 'Here is a photo of my family.', correct: 'photo', choices: ['photo', 'phone', 'picture', 'piano'] },
      { sentence: 'Who is the girl?', correct: 'girl', choices: ['girl', 'goal', 'golf', 'guard'] },
      { sentence: 'They are my cousins.', correct: 'cousins', choices: ['cousins', 'cousin', 'causes', 'courses'] },
      { sentence: 'My aunt works in a hospital.', correct: 'aunt', choices: ['aunt', 'ant', 'and', 'end'] },
      { sentence: 'The baby is only two.', correct: 'baby', choices: ['baby', 'body', 'busy', 'maybe'] },
    ],
  },
  {
    order: 3,
    chapter: '七上 Unit 3',
    title: 'Is This Your Pencil?',
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 3',
    learn: [
      ['Is this your pencil?', ['Is', 'this', 'your', 'pencil?']],
      ['Excuse me, is that hers?', ['Excuse', 'me,', 'is', 'that', 'hers?']],
    ],
    listen: [
      { sentence: 'This is my schoolbag.', correct: 'schoolbag', choices: ['schoolbag', 'notebook', 'backpack', 'handbag'] },
      { sentence: 'The dictionary is mine.', correct: 'dictionary', choices: ['dictionary', 'direction', 'station', 'fiction'] },
      { sentence: 'I lost my eraser.', correct: 'eraser', choices: ['eraser', 'reader', 'ruler', 'razor'] },
      { sentence: 'Please call me at five.', correct: 'call', choices: ['call', 'cold', 'cool', 'cell'] },
      { sentence: 'The ring is not for sale.', correct: 'ring', choices: ['ring', 'bring', 'sing', 'wing'] },
      { sentence: 'Thank you for your help.', correct: 'help', choices: ['help', 'held', 'hell', 'heap'] },
    ],
  },
  {
    order: 4,
    chapter: '七上 Unit 4',
    title: "Where's My Schoolbag?",
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 4',
    learn: [
      ['Where is my schoolbag?', ['Where', 'is', 'my', 'schoolbag?']],
      ['It is under the table.', ['It', 'is', 'under', 'the', 'table.']],
    ],
    listen: [
      { sentence: 'The keys are on the sofa.', correct: 'sofa', choices: ['sofa', 'soft', 'safe', 'soap'] },
      { sentence: 'Your books are in the bookcase.', correct: 'bookcase', choices: ['bookcase', 'bookshop', 'backpack', 'notebook'] },
      { sentence: 'The model plane is tidy.', correct: 'model', choices: ['model', 'middle', 'modal', 'moral'] },
      { sentence: 'Come on, we are late.', correct: 'late', choices: ['late', 'let', 'lake', 'last'] },
      { sentence: 'I need my English book.', correct: 'need', choices: ['need', 'read', 'lead', 'feed'] },
      { sentence: 'Everything is in the room.', correct: 'Everything', choices: ['Everything', 'Everyone', 'Everyday', 'Every'] },
    ],
  },
  {
    order: 5,
    chapter: '七上 Unit 5',
    title: 'Do You Have a Soccer Ball?',
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 5',
    learn: [
      ['Do you have a soccer ball?', ['Do', 'you', 'have', 'a', 'soccer', 'ball?']],
      ['Let us play ping-pong after class.', ['Let', 'us', 'play', 'ping-pong', 'after', 'class.']],
    ],
    listen: [
      { sentence: 'I love sports very much.', correct: 'sports', choices: ['sports', 'spots', 'shorts', 'sorts'] },
      { sentence: 'We have a tennis racket.', correct: 'tennis', choices: ['tennis', 'dinner', 'penny', 'badminton'] },
      { sentence: 'He only watches them on TV.', correct: 'watches', choices: ['watches', 'washes', 'matches', 'catch'] },
      { sentence: 'That sounds interesting.', correct: 'interesting', choices: ['interesting', 'interested', 'internet', 'instrument'] },
      { sentence: 'It is easy for me.', correct: 'easy', choices: ['easy', 'busy', 'lazy', 'crazy'] },
      { sentence: 'Let us go to the same school.', correct: 'same', choices: ['same', 'some', 'seem', 'save'] },
    ],
  },
  {
    order: 6,
    chapter: '七上 Unit 6',
    title: 'Do You Like Bananas?',
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 6',
    learn: [
      ['Do you like bananas?', ['Do', 'you', 'like', 'bananas?']],
      ['I like apples and salad.', ['I', 'like', 'apples', 'and', 'salad.']],
    ],
    listen: [
      { sentence: 'How about some bread?', correct: 'bread', choices: ['bread', 'break', 'bring', 'broad'] },
      { sentence: 'Ice-cream is not healthy.', correct: 'healthy', choices: ['healthy', 'health', 'heavy', 'heaven'] },
      { sentence: 'Chicken is my favourite.', correct: 'Chicken', choices: ['Chicken', 'Kitchen', 'Children', 'Chichen'] },
      { sentence: 'We eat breakfast at seven.', correct: 'breakfast', choices: ['breakfast', 'break', 'breath', 'breast'] },
      { sentence: 'The fruit is fresh.', correct: 'fruit', choices: ['fruit', 'foot', 'free', 'front'] },
      { sentence: 'I really love vegetables.', correct: 'vegetables', choices: ['vegetables', 'tables', 'animals', 'examples'] },
    ],
  },
  {
    order: 7,
    chapter: '七上 Unit 7',
    title: 'How Much Are These Socks?',
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 7',
    learn: [
      ['How much is this T-shirt?', ['How', 'much', 'is', 'this', 'T-shirt?']],
      ['I will take the blue sweater.', ['I', 'will', 'take', 'the', 'blue', 'sweater.']],
    ],
    listen: [
      { sentence: 'The socks are only two dollars.', correct: 'dollars', choices: ['dollars', 'dollar', 'doors', 'dolls'] },
      { sentence: 'We sell trousers in many colours.', correct: 'trousers', choices: ['trousers', 'trouser', 'traces', 'towers'] },
      { sentence: 'The skirt looks nice.', correct: 'skirt', choices: ['skirt', 'shirt', 'short', 'start'] },
      { sentence: 'Can I help you today?', correct: 'help', choices: ['help', 'held', 'hop', 'hope'] },
      { sentence: 'Here is a big sale.', correct: 'sale', choices: ['sale', 'sail', 'safe', 'same'] },
      { sentence: 'I need a pair of shoes.', correct: 'pair', choices: ['pair', 'pear', 'poor', 'pure'] },
    ],
  },
  {
    order: 8,
    chapter: '七上 Unit 8',
    title: 'When Is Your Birthday?',
    textbook: '风格参考：人教版《英语》七年级上册 · Unit 8',
    learn: [
      ['When is your birthday party?', ['When', 'is', 'your', 'birthday', 'party?']],
      ['My birthday is in September.', ['My', 'birthday', 'is', 'in', 'September.']],
    ],
    listen: [
      { sentence: 'The school trip is in October.', correct: 'October', choices: ['October', 'November', 'December', 'August'] },
      { sentence: 'We have an art festival.', correct: 'festival', choices: ['festival', 'festive', 'fatal', 'fossil'] },
      { sentence: 'Happy birthday to you.', correct: 'birthday', choices: ['birthday', 'Thursday', 'holiday', 'birth'] },
      { sentence: 'This term is busy.', correct: 'term', choices: ['term', 'team', 'time', 'turn'] },
      { sentence: 'The English test is next week.', correct: 'test', choices: ['test', 'text', 'taste', 'toast'] },
      { sentence: 'See you at the party.', correct: 'party', choices: ['party', 'park', 'part', 'pass'] },
    ],
  },
  {
    order: 9,
    chapter: '七下 Unit 1',
    title: 'Can You Play the Guitar?',
    textbook: '风格参考：人教版《英语》七年级下册 · Unit 1',
    learn: [
      ['Can you play the guitar?', ['Can', 'you', 'play', 'the', 'guitar?']],
      ['I want to join the music club.', ['I', 'want', 'to', 'join', 'the', 'music', 'club.']],
    ],
    listen: [
      { sentence: 'She can swim very well.', correct: 'swim', choices: ['swim', 'swing', 'sweet', 'swift'] },
      { sentence: 'He draws pictures every day.', correct: 'draws', choices: ['draws', 'dress', 'drops', 'drums'] },
      { sentence: 'Tell stories at the party.', correct: 'stories', choices: ['stories', 'stores', 'studies', 'scores'] },
      { sentence: 'We need students for the show.', correct: 'students', choices: ['students', 'student', 'studies', 'studios'] },
      { sentence: 'Are you free on Sunday?', correct: 'free', choices: ['free', 'three', 'tree', 'fry'] },
      { sentence: 'Talk to Mr Miller after class.', correct: 'Talk', choices: ['Talk', 'Walk', 'Take', 'Task'] },
    ],
  },
  {
    order: 10,
    chapter: '八上 Unit 1',
    title: 'Where Did You Go on Vacation?',
    textbook: '风格参考：人教版《英语》八年级上册 · Unit 1',
    learn: [
      ['I went to the mountains with my family.', ['I', 'went', 'to', 'the', 'mountains', 'with', 'my', 'family.']],
      ['It was sunny and warm.', ['It', 'was', 'sunny', 'and', 'warm.']],
    ],
    listen: [
      { sentence: 'We visited the science museum.', correct: 'museum', choices: ['museum', 'music', 'medium', 'moment'] },
      { sentence: 'The food tasted really good.', correct: 'tasted', choices: ['tasted', 'tested', 'tasked', 'toasted'] },
      { sentence: 'I felt tired but happy.', correct: 'tired', choices: ['tired', 'tried', 'tiled', 'tiered'] },
      { sentence: 'Did you go with anyone?', correct: 'anyone', choices: ['anyone', 'anyway', 'anything', 'anywhere'] },
      { sentence: 'Nothing felt boring there.', correct: 'boring', choices: ['boring', 'bring', 'boiling', 'boarding'] },
      { sentence: 'I bought something for you.', correct: 'bought', choices: ['bought', 'brought', 'bright', 'board'] },
    ],
  },
  {
    order: 11,
    chapter: '八上 Unit 2',
    title: 'How Often Do You Exercise?',
    textbook: '风格参考：人教版《英语》八年级上册 · Unit 2',
    learn: [
      ['How often do you watch TV?', ['How', 'often', 'do', 'you', 'watch', 'TV?']],
      ['I exercise three times a week.', ['I', 'exercise', 'three', 'times', 'a', 'week.']],
    ],
    listen: [
      { sentence: 'I use the Internet every day.', correct: 'Internet', choices: ['Internet', 'Interest', 'Interview', 'Internal'] },
      { sentence: 'She hardly ever plays games.', correct: 'hardly', choices: ['hardly', 'hardy', 'nearly', 'really'] },
      { sentence: 'Once a month is enough.', correct: 'month', choices: ['month', 'mouth', 'moth', 'mount'] },
      { sentence: 'Junk food is bad for health.', correct: 'health', choices: ['health', 'healthy', 'wealth', 'hearth'] },
      { sentence: 'My lifestyle is quite healthy.', correct: 'lifestyle', choices: ['lifestyle', 'lifetime', 'live', 'lift'] },
      { sentence: 'We should get enough sleep.', correct: 'sleep', choices: ['sleep', 'slip', 'sheep', 'steep'] },
    ],
  },
  {
    order: 12,
    chapter: '八年级 Unit 3',
    title: 'Could You Please Clean Your Room?',
    textbook: '风格参考：人教版《英语》八年级下册 · Unit 3',
    learn: [
      ['Could you please take out the rubbish?', ['Could', 'you', 'please', 'take', 'out', 'the', 'rubbish?']],
      ['I will fold the clothes later.', ['I', 'will', 'fold', 'the', 'clothes', 'later.']],
    ],
    listen: [
      { sentence: 'Could you sweep the floor?', correct: 'sweep', choices: ['sweep', 'sweet', 'sleep', 'swipe'] },
      { sentence: 'Please fold your shirt.', correct: 'fold', choices: ['fold', 'folk', 'food', 'fond'] },
      { sentence: 'Pass me the rubbish bag.', correct: 'rubbish', choices: ['rubbish', 'rabbit', 'ribbon', 'rubber'] },
      { sentence: 'I need to do chores.', correct: 'chores', choices: ['chores', 'choirs', 'chairs', 'cheers'] },
      { sentence: 'Could I stay out late?', correct: 'stay', choices: ['stay', 'say', 'stays', 'steak'] },
      { sentence: 'Thanks for taking care of the dog.', correct: 'care', choices: ['care', 'car', 'core', 'card'] },
    ],
  },
]
