/**
 * 小学：人教版（PEP）三起教材风格 · 原创示例（非教材原文）
 * 每单元对应「册 + Unit」常见主题。
 */
export const primaryUnits = [
  {
    order: 1,
    chapter: '三上 Unit 1',
    title: 'Hello!',
    textbook: '风格参考：人教版（PEP）三年级上册 · Unit 1',
    learn: [
      ["Hello, I'm Sarah.", ['Hello,', "I'm", 'Sarah.']],
      ['Nice to meet you.', ['Nice', 'to', 'meet', 'you.']],
    ],
    listen: [
      { sentence: 'This is my new friend.', correct: 'friend', choices: ['friend', 'teacher', 'sister', 'brother'] },
      { sentence: 'Good morning, Miss White.', correct: 'morning', choices: ['morning', 'evening', 'afternoon', 'night'] },
      { sentence: 'I have a pencil box.', correct: 'pencil', choices: ['pencil', 'crayon', 'crayons', 'paper'] },
      { sentence: 'Goodbye, see you later.', correct: 'later', choices: ['later', 'letter', 'listen', 'little'] },
      { sentence: 'What is your name?', correct: 'name', choices: ['name', 'game', 'same', 'face'] },
      { sentence: 'Let us go to school.', correct: 'school', choices: ['school', 'home', 'room', 'house'] },
    ],
  },
  {
    order: 2,
    chapter: '三上 Unit 2',
    title: 'Colours',
    textbook: '风格参考：人教版（PEP）三年级上册 · Unit 2',
    learn: [
      ['I see red and blue.', ['I', 'see', 'red', 'and', 'blue.']],
      ['What colour is the apple?', ['What', 'colour', 'is', 'the', 'apple?']],
    ],
    listen: [
      { sentence: 'The sky is blue today.', correct: 'blue', choices: ['blue', 'black', 'brown', 'blame'] },
      { sentence: 'I like green trees.', correct: 'green', choices: ['green', 'great', 'grape', 'grow'] },
      { sentence: 'This is a yellow banana.', correct: 'yellow', choices: ['yellow', 'young', 'yell', 'year'] },
      { sentence: 'Colour it orange.', correct: 'orange', choices: ['orange', 'open', 'order', 'once'] },
      { sentence: 'Pink is my favourite colour.', correct: 'Pink', choices: ['Pink', 'Pick', 'Pack', 'Park'] },
      { sentence: 'Show me the black cat.', correct: 'black', choices: ['black', 'back', 'block', 'blank'] },
    ],
  },
  {
    order: 3,
    chapter: '三上 Unit 3',
    title: 'Look at Me!',
    textbook: '风格参考：人教版（PEP）三年级上册 · Unit 3',
    learn: [
      ['Look at my face.', ['Look', 'at', 'my', 'face.']],
      ['I have two big eyes.', ['I', 'have', 'two', 'big', 'eyes.']],
    ],
    listen: [
      { sentence: 'Touch your nose.', correct: 'nose', choices: ['nose', 'rose', 'note', 'knows'] },
      { sentence: 'Open your mouth.', correct: 'mouth', choices: ['mouth', 'month', 'mouse', 'mount'] },
      { sentence: 'This is my arm.', correct: 'arm', choices: ['arm', 'farm', 'art', 'aim'] },
      { sentence: 'Wave your hand.', correct: 'hand', choices: ['hand', 'head', 'hat', 'hang'] },
      { sentence: 'Stamp your foot.', correct: 'foot', choices: ['foot', 'food', 'four', 'full'] },
      { sentence: 'Clap your hands.', correct: 'hands', choices: ['hands', 'hand', 'lands', 'bands'] },
    ],
  },
  {
    order: 4,
    chapter: '三上 Unit 4',
    title: 'We Love Animals',
    textbook: '风格参考：人教版（PEP）三年级上册 · Unit 4',
    learn: [
      ['I see a duck on the farm.', ['I', 'see', 'a', 'duck', 'on', 'the', 'farm.']],
      ['The cat is cute.', ['The', 'cat', 'is', 'cute.']],
    ],
    listen: [
      { sentence: 'This is a funny bird.', correct: 'bird', choices: ['bird', 'bear', 'boat', 'book'] },
      { sentence: 'The pig is fat.', correct: 'pig', choices: ['pig', 'big', 'dig', 'pin'] },
      { sentence: 'I have a pet dog.', correct: 'dog', choices: ['dog', 'duck', 'door', 'desk'] },
      { sentence: 'The elephant is big.', correct: 'elephant', choices: ['elephant', 'animal', 'element', 'elegant'] },
      { sentence: 'Look at the monkey.', correct: 'monkey', choices: ['monkey', 'money', 'monthly', 'many'] },
      { sentence: 'A tiger runs fast.', correct: 'tiger', choices: ['tiger', 'timer', 'lion', 'bear'] },
    ],
  },
  {
    order: 5,
    chapter: '三上 Unit 5',
    title: "Let's Eat!",
    textbook: '风格参考：人教版（PEP）三年级上册 · Unit 5',
    learn: [
      ['Have some bread.', ['Have', 'some', 'bread.']],
      ['I drink milk every day.', ['I', 'drink', 'milk', 'every', 'day.']],
    ],
    listen: [
      { sentence: 'I would like some juice.', correct: 'juice', choices: ['juice', 'rice', 'ice', 'nice'] },
      { sentence: 'Pass me the egg.', correct: 'egg', choices: ['egg', 'leg', 'bag', 'big'] },
      { sentence: 'The fish is fresh.', correct: 'fish', choices: ['fish', 'dish', 'wish', 'finish'] },
      { sentence: 'Cut the cake with care.', correct: 'cake', choices: ['cake', 'take', 'make', 'lake'] },
      { sentence: 'I have a hot dog.', correct: 'hot', choices: ['hot', 'hat', 'hit', 'lot'] },
      { sentence: 'Vegetables are good for you.', correct: 'Vegetables', choices: ['Vegetables', 'Animals', 'Tables', 'Examples'] },
    ],
  },
  {
    order: 6,
    chapter: '三上 Unit 6',
    title: 'Happy Birthday!',
    textbook: '风格参考：人教版（PEP）三年级上册 · Unit 6',
    learn: [
      ['How old are you?', ['How', 'old', 'are', 'you?']],
      ["I'm six years old.", ["I'm", 'six', 'years', 'old.']],
    ],
    listen: [
      { sentence: 'Happy birthday to you.', correct: 'birthday', choices: ['birthday', 'Thursday', 'holiday', 'day'] },
      { sentence: 'I am seven years old.', correct: 'seven', choices: ['seven', 'eleven', 'even', 'oven'] },
      { sentence: 'This is my gift.', correct: 'gift', choices: ['gift', 'lift', 'give', 'left'] },
      { sentence: 'Make a wish.', correct: 'wish', choices: ['wish', 'fish', 'wash', 'which'] },
      { sentence: 'The candle is on the cake.', correct: 'candle', choices: ['candle', 'handle', 'kindle', 'saddle'] },
      { sentence: 'Thank you for the party.', correct: 'party', choices: ['party', 'pretty', 'park', 'paper'] },
    ],
  },
  {
    order: 7,
    chapter: '三下 Unit 1',
    title: 'Welcome Back to School',
    textbook: '风格参考：人教版（PEP）三年级下册 · Unit 1',
    learn: [
      ['Nice to see you again.', ['Nice', 'to', 'see', 'you', 'again.']],
      ['We are back at school.', ['We', 'are', 'back', 'at', 'school.']],
    ],
    listen: [
      { sentence: 'This is the UK flag.', correct: 'flag', choices: ['flag', 'flat', 'flow', 'fly'] },
      { sentence: 'She is from Canada.', correct: 'Canada', choices: ['Canada', 'China', 'America', 'Africa'] },
      { sentence: 'He is a new student.', correct: 'student', choices: ['student', 'teacher', 'children', 'parent'] },
      { sentence: 'Where are you from?', correct: 'from', choices: ['from', 'form', 'farm', 'front'] },
      { sentence: 'Welcome to our class.', correct: 'Welcome', choices: ['Welcome', 'Well', 'Will', 'While'] },
      { sentence: 'Good to see you again.', correct: 'again', choices: ['again', 'against', 'garden', 'gain'] },
    ],
  },
  {
    order: 8,
    chapter: '三下 Unit 2',
    title: 'My Family',
    textbook: '风格参考：人教版（PEP）三年级下册 · Unit 2',
    learn: [
      ['This is my father.', ['This', 'is', 'my', 'father.']],
      ['She is my mother.', ['She', 'is', 'my', 'mother.']],
    ],
    listen: [
      { sentence: 'This is my sister.', correct: 'sister', choices: ['sister', 'brother', 'mother', 'father'] },
      { sentence: 'My grandfather is tall.', correct: 'grandfather', choices: ['grandfather', 'grandmother', 'grandson', 'grand'] },
      { sentence: 'The baby is cute.', correct: 'baby', choices: ['baby', 'maybe', 'body', 'busy'] },
      { sentence: 'Is that your uncle?', correct: 'uncle', choices: ['uncle', 'aunt', 'ant', 'unit'] },
      { sentence: 'My cousin is a boy.', correct: 'cousin', choices: ['cousin', 'cousins', 'cause', 'caution'] },
      { sentence: 'We love our family.', correct: 'family', choices: ['family', 'famous', 'finally', 'friendly'] },
    ],
  },
  {
    order: 9,
    chapter: '四上 Unit 1',
    title: 'My Classroom',
    textbook: '风格参考：人教版（PEP）四年级上册 · Unit 1',
    learn: [
      ['We have a new classroom.', ['We', 'have', 'a', 'new', 'classroom.']],
      ['Let us clean the windows.', ['Let', 'us', 'clean', 'the', 'windows.']],
    ],
    listen: [
      { sentence: 'This is our classroom.', correct: 'classroom', choices: ['classroom', 'classmate', 'class', 'room'] },
      { sentence: 'Turn on the computer.', correct: 'computer', choices: ['computer', 'picture', 'paper', 'popular'] },
      { sentence: 'The fan is on the wall.', correct: 'fan', choices: ['fan', 'fun', 'fine', 'fan'] },
      { sentence: 'Put the book in the desk.', correct: 'desk', choices: ['desk', 'disk', 'dust', 'ask'] },
      { sentence: 'Where is the light?', correct: 'light', choices: ['light', 'night', 'right', 'fight'] },
      { sentence: 'The floor is clean.', correct: 'floor', choices: ['floor', 'flower', 'fly', 'flow'] },
    ],
  },
  {
    order: 10,
    chapter: '四上 Unit 2',
    title: 'My Schoolbag',
    textbook: '风格参考：人教版（PEP）四年级上册 · Unit 2',
    learn: [
      ['What is in your schoolbag?', ['What', 'is', 'in', 'your', 'schoolbag?']],
      ['An English book and a notebook.', ['An', 'English', 'book', 'and', 'a', 'notebook.']],
    ],
    listen: [
      { sentence: 'I lost my maths book.', correct: 'maths', choices: ['maths', 'maps', 'match', 'mass'] },
      { sentence: 'This is a Chinese book.', correct: 'Chinese', choices: ['Chinese', 'English', 'Japan', 'science'] },
      { sentence: 'Put the key in the bag.', correct: 'key', choices: ['key', 'kid', 'keep', 'kind'] },
      { sentence: 'I have a candy in the box.', correct: 'candy', choices: ['candy', 'candy', 'candle', 'Sunday'] },
      { sentence: 'The storybook is fun.', correct: 'storybook', choices: ['storybook', 'notebook', 'textbook', 'workbook'] },
      { sentence: 'The toy is in the box.', correct: 'toy', choices: ['toy', 'boy', 'try', 'day'] },
    ],
  },
  {
    order: 11,
    chapter: '四上 Unit 3',
    title: 'My Friends',
    textbook: '风格参考：人教版（PEP）四年级上册 · Unit 3',
    learn: [
      ['He is tall and strong.', ['He', 'is', 'tall', 'and', 'strong.']],
      ['She has long hair.', ['She', 'has', 'long', 'hair.']],
    ],
    listen: [
      { sentence: 'My friend is quiet.', correct: 'quiet', choices: ['quiet', 'quite', 'quick', 'queen'] },
      { sentence: 'He is very friendly.', correct: 'friendly', choices: ['friendly', 'family', 'finally', 'freely'] },
      { sentence: 'Her shoes are blue.', correct: 'shoes', choices: ['shoes', 'shows', 'choose', 'shoe'] },
      { sentence: 'His glasses are black.', correct: 'glasses', choices: ['glasses', 'classes', 'grasses', 'grass'] },
      { sentence: 'She is a cute girl.', correct: 'girl', choices: ['girl', 'gill', 'goal', 'give'] },
      { sentence: 'We play together after school.', correct: 'together', choices: ['together', 'tomorrow', 'weather', 'gather'] },
    ],
  },
  {
    order: 12,
    chapter: '五上 Unit 1',
    title: "What's He Like?",
    textbook: '风格参考：人教版（PEP）五年级上册 · Unit 1',
    learn: [
      ['Mr Young is our music teacher.', ['Mr', 'Young', 'is', 'our', 'music', 'teacher.']],
      ['She is kind but sometimes strict.', ['She', 'is', 'kind', 'but', 'sometimes', 'strict.']],
    ],
    listen: [
      { sentence: 'He is a clever boy.', correct: 'clever', choices: ['clever', 'never', 'level', 'silver'] },
      { sentence: 'She is very polite.', correct: 'polite', choices: ['polite', 'police', 'plate', 'planet'] },
      { sentence: 'The head teacher is strict.', correct: 'strict', choices: ['strict', 'street', 'string', 'stick'] },
      { sentence: 'Is he helpful at home?', correct: 'helpful', choices: ['helpful', 'hopeful', 'useful', 'careful'] },
      { sentence: 'My art teacher is funny.', correct: 'funny', choices: ['funny', 'sunny', 'money', 'honey'] },
      { sentence: 'We will work hard this term.', correct: 'hard', choices: ['hard', 'hand', 'heart', 'heard'] },
    ],
  },
]
